apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactive-resume
  namespace: default

spec:
  replicas: 1

  selector:
    matchLabels:
      app: reactive-resume

  template:
    metadata:
      labels:
        app: reactive-resume

    spec:
      containers:
        - name: reactive-resume
          image: amruthpillai/reactive-resume:latest

          ports:
            - containerPort: 3000

          env:
            - name: TRUST_PROXY
              value: "true"
              
            - name: APP_URL
              value: "http://makemycv.mihir.uk"

            - name: DATABASE_URL
              value: "postgresql://resume:change-me@reactive-resume-postgres:5432/resume"

            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: reactive-resume-secret
                  key: AUTH_SECRET