apiVersion: v1
kind: Secret
metadata:
  name: reactive-resume-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_PASSWORD: "change-me"
  AUTH_SECRET: "171bb973af87efb1f3bd68a6a11bb56241d5803116455e984c3064bdd81a200c"